require_relative("lib/board")
require_relative("lib/chess")
require_relative("lib/pieces/bishop")
require_relative("lib/pieces/king")
require_relative("lib/pieces/knight")
require_relative("lib/pieces/pawn")
require_relative("lib/pieces/piece")
require_relative("lib/pieces/queen")
require_relative("lib/pieces/rook")

board = Board.new()
p(board.grid[1][0].moves)
p(board.grid[1][0].colour)